// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onzrvugzzqadcsofxcub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uenJ2dWd6enFhZGNzb2Z4Y3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MjIyOTQsImV4cCI6MjA3NDA5ODI5NH0.voBSTrMYY1O1qOThSfx0vzlU5TDzc31uBRqQbBvxrfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});